### ISSUE TITLE
Add a Nice logo & a favicon 

### ISSUE THREAD

**Issue by rahulkamilya** [rahulkamilya/ID-Verifier#10]

**Comment by bishwobista** [comment]
Hey, What do we need here?
Assign me this issue

**Comment by rahulkamilya** [comment]
@bishwobista I need Interactive,

will you do that ??

**Comment by bishwobista** [comment]
yea I can do that, How interactive? How do you want the logo and favicon? You have any ideas?

**Comment by rahulkamilya** [comment]
@bishwobista Yeah, Change default logo's to your logo, Make Sure It'll Interactive

**Comment by Sha1kh4** [comment]
@rahulkamilya Please , explain how a logo can be  Interactive.

**Comment by rahulkamilya** [comment]
> @rahulkamilya Please , explain how a logo can be Interactive.

Hey @Sha1kh4 , Make with your Own Choice (":
