### ISSUE TITLE
Add transparent "XXXX-XXXX-XXXX" On Search bar 

### ISSUE THREAD

**Issue by rahulkamilya** [rahulkamilya/ID-Verifier#11]
Add a transparent 12 digit "XXXX-XXXX-XXXX" On Search bar like debit card

**Comment by aman999au** [comment]
Please assign this to me

**Comment by rahulkamilya** [comment]
Hey @Aman0786-git Will you do that Properly ?

**Comment by aman999au** [comment]
yeah will try , I am working with frontend for a quite long time

**Comment by rahulkamilya** [comment]
@Aman0786-git Assigned

**Comment by aman999au** [comment]
Is it what you needed or i have to make changes in CSS also ?
And if it is not what you want please describe the issue. 
Thankyou
![Screenshot 2023-10-01 095555](https://github.com/rahulkamilya/ID-Verifier/assets/91136984/85275216-d285-4cca-885f-8b7faee34ba7)

**Comment by rahulkamilya** [comment]
@Aman0786-git yes, I need that kind of changes, make it for web as well as mobile view also
