### ISSUE TITLE
Write a Super Interactive readme file for better understanding

### ISSUE THREAD

**Issue by rahulkamilya** [rahulkamilya/ID-Verifier#12]
Read my previous readme file, Rewrite it a better way

**Comment by Esha-in-arena** [comment]
Hey ! @rahulkamilya I can do it . Could you please assign this to me

**Comment by rahulkamilya** [comment]
@Esha-01 , I see you doesn't include anything for your own readme file !
Will you really make it Interactive 🥲?

**Comment by Esha-in-arena** [comment]
@rahulkamilya  at least i can try if u assign it 😢

**Comment by rahulkamilya** [comment]
okayy @Esha-01 Try karke dekho

**Comment by anubhav1206** [comment]
Can I work on it with @Esha-01 ?

**Comment by rahulkamilya** [comment]
> Can I work on it with @Esha-01 ?

@anubhav1206 If you want you can try (":

**Comment by gautamb02** [comment]
Hey, I'm happy to help!!

**Comment by rahulkamilya** [comment]
> Hey, I'm happy to help!!

@gautam-bhagat You R in
