### ISSUE TITLE
Add Team Section to Webpage

### ISSUE THREAD

**Issue by premsaivarmachekuri** [rahulkamilya/ID-Verifier#15]
## Description

Currently, our navigation bar features a "Team" element, but there is no corresponding section or page dedicated to showcasing our contributors and team members. This enhancement request aims to add a "Team" section to our webpage, allowing us to display contributor profiles and provide recognition to the valuable individuals behind our project.

## How to Reproduce

1) Go to the application.
2) Navigate to the Team section on the Navbar.

## Expected Behavior

The expected behavior is to introduce a "Team" section accessible via the navigation bar. This section will:

- Display contributor profiles or cards, providing a brief introduction to each team member.
- Include links to individual profiles or more detailed information, if available.
- Enhance our project's transparency and recognition of contributors.

## Screenshots

![image](https://github.com/rahulkamilya/ID-Verifier/assets/110842297/caf473a2-ed1e-436e-8dea-bea76284178a)

## Additional Content

Adding a "Team" section to our webpage not only improves user experience but also acknowledges the efforts and contributions of our team members. It fosters a sense of community and transparency within our project.

🌟 **Note**: Please ensure that all required tasks are completed before submitting your issue/PR:

- [x] I have checked for existing issues related to this enhancement.
- [x] [Give a Star](https://github.com/YourRepository/YourProject) ⭐
- [x] Have you added your name in [CONTRIBUTING.md](https://github.com/rahulkamilya/ID-Verifier/blob/main/CONTRIBUTING.md)
- [x] I would like to work on this issue

**Comment by rahulkamilya** [comment]
Hello @premsaivarmachekuri , are you there ?

**Comment by premsaivarmachekuri** [comment]
Yeah, I am there. I am working on it. Will be updating soon.

**Comment by rahulkamilya** [comment]
Okay @premsaivarmachekuri
