### ISSUE TITLE
No default 404 page present

### ISSUE THREAD

**Issue by Ritesh-Dabral** [rahulkamilya/ID-Verifier#19]
The app's 404 page and routes are missing, which forces the app to open vercel's 404 page, which break the UX consistency.

<img width="1201" alt="Screenshot 2023-10-01 at 2 29 49 PM" src="https://github.com/rahulkamilya/ID-Verifier/assets/36252036/c7e2e220-a8a7-4f13-8420-00d6147db11e">

**Comment by Ritesh-Dabral** [comment]
@rahulkamilya Please assign this issue to me

**Comment by rahulkamilya** [comment]
Okky, Do it @Ritesh-Dabral

**Comment by Ritesh-Dabral** [comment]
<img width="373" alt="Screenshot 2023-10-01 at 3 54 46 PM" src="https://github.com/rahulkamilya/ID-Verifier/assets/36252036/b8034a21-4617-4c62-9795-6848522a4722">
<img width="1469" alt="Screenshot 2023-10-01 at 3 54 24 PM" src="https://github.com/rahulkamilya/ID-Verifier/assets/36252036/0d331bfd-ab3d-4b57-ac4a-79b26ac98864">


@rahulkamilya Kindly verify the design. Post that I will raise the PR

**Comment by gautamb02** [comment]
Rahul,
I'm proficient with react i might help
