### ISSUE TITLE
Add a About Page 

### ISSUE THREAD

**Issue by rahulkamilya** [rahulkamilya/ID-Verifier#27]
Add a About Page, Write Something about our website .

Happy Hacking (":

**Comment by shreyanshig** [comment]
Hello @rahulkamilya, can you please assign this issue to me?

**Comment by rahulkamilya** [comment]
okky do it @shreyanshig

**Comment by rahulkamilya** [comment]
@shreyanshig ??

**Comment by shreyanshig** [comment]
I made the about page using html and css. And I am not introduced to react.
So,I am unable to link the button with exact page
