### ISSUE TITLE
Design A Unique Logo of VeriDy

### ISSUE THREAD

**Issue by rahulkamilya** [rahulkamilya/ID-Verifier#28]
Before Start Contributing Star Our Repo 🌟

**Comment by riyajath-ahamed** [comment]
@rahulkamilya can Non - contributors participate ?

**Comment by rahulkamilya** [comment]
Yup @riyajath-ahamed , But you have to design and add logo

**Comment by riyajath-ahamed** [comment]
@rahulkamilya Give a short Brief How the Logo Should be.

**Comment by rahulkamilya** [comment]
> @rahulkamilya Give a short Brief How the Logo Should be.

@riyajath-ahamed Kind of Verification logo

**Comment by gautamb02** [comment]
Hey Rahul, 
I will be happy to contribute and solve the issue for you !!

**Comment by rahulkamilya** [comment]
> Hey Rahul, I will be happy to contribute and solve the issue for you !!

@gautam-bhagat Assigned
