### ISSUE TITLE
Write a Super Interactive readme file for better understanding

### ISSUE THREAD

**Issue by rahulkamilya** [rahulkamilya/ID-Verifier#34]

**Comment by Pr0-C0der** [comment]
Hey, I can contribute to this issue @rahulkamilya. Can you give me a brief on what contents the readme file should contain? Also assign this issue to me

**Comment by Shashankpantiitbhilai** [comment]
I want to work on it,please assign it to me?

**Comment by rahulkamilya** [comment]
> I want to work on it,please assign it to me?

@Shashankpantiitbhilai you are in 

🌟 Our Repo

**Comment by Shashankpantiitbhilai** [comment]
sure sir
