### ISSUE TITLE
Add a search option in Team and configure the navbar for active page to have different color than other pages

### ISSUE THREAD

**Issue by ShahIsCoding** [rahulkamilya/ID-Verifier#38]
I found two issue in team & navbar

1. there is no search bar in team and as the teams grows it will be needed,
2. Edit the navbar to remove the unused button and for active page to have different color

**Comment by Shashankpantiitbhilai** [comment]
assign it to me

**Comment by rahulkamilya** [comment]
@ShahIsCoding Do it

**Comment by ShahIsCoding** [comment]
solved
