### ISSUE TITLE
[Feature]: enhance ui of contributor card

### ISSUE THREAD

**Issue by irshadsiddi** [rahulkamilya/ID-Verifier#49]
### Description

want to add gradient border for the contributor card in the team page.
![Screenshot from 2024-10-24 22-06-29](https://github.com/user-attachments/assets/1030b40d-6b86-40d1-9b46-3adb126f7719)

### Provide Screenshot

![Screenshot from 2024-10-24 20-11-40](https://github.com/user-attachments/assets/0992fe7e-8dcd-43d3-84ff-e2445b5bf8b5)
want to add border gradient like this.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/PriyansuMaurya/AI-Fusion/blob/main/CONTRIBUTING.md).
- [X] I am willing to work on this issue (optional)

**Comment by rahulkamilya** [comment]
Do it, you may enhance some additional features whatever you like to see website looks beautiful.

**Comment by rahulkamilya** [comment]
I'll marge as hacktoberfest accept badge

**Comment by irshadsiddi** [comment]
yeah, please add hacktoberfest label and after completion i'll send you a preview screenshot of the screen.
