### ISSUE TITLE
Add Cursor as Pointer to Navbar 

### ISSUE THREAD

**Issue by rahulkamilya** [rahulkamilya/ID-Verifier#5]

**Comment by bharath090909** [comment]
@rahulkamilya can i take up this issue ?

**Comment by akadeepesh** [comment]
@rahulkamilya I can solve this issue, please assign it to me.

**Comment by rahulkamilya** [comment]
Okay you can

**Comment by Vervesandip** [comment]
@rahulkamilya I can solve this issue.
