### ISSUE TITLE
Unnecessary API calls

### ISSUE THREAD

**Issue by aanchal-fatwani** [rahulkamilya/ID-Verifier#8]
@rahulkamilya  As part of HacktoberFest2023, I wish to improve the logical handling of the user input. I wish to add validation of user input to reduce API calls thus improving the application logic.
Please assign this issue to me if you're fine accepting this issue for the improvement of this project and HacktoberFest submission.

**Comment by rahulkamilya** [comment]
> @rahulkamilya As part of HacktoberFest2023, I wish to improve the logical handling of the user input. I wish to add validation of user input to reduce API calls thus improving the application logic. Please assign this issue to me if you're fine accepting this issue for the improvement of this project and HacktoberFest submission.

Do it

**Comment by rahulkamilya** [comment]
Hey @aanchal-fatwani fix Unnecessary API calls, I'II marge it surely.
