### ISSUE TITLE
Improve UI of search bar

### ISSUE THREAD

**Issue by aanchal-fatwani** [rahulkamilya/ID-Verifier#9]
@rahulkamilya As part of HacktoberFest2023, I wish to improve the UI of the search bar and button.
Please assign this issue to me if you're fine accepting this issue for the improvement of this project and HacktoberFest submission.

![image](https://github.com/rahulkamilya/ID-Verifier/assets/63228776/e93047f3-6e68-4cfe-ad87-c2fcb653d830)

**Comment by rahulkamilya** [comment]
@aanchal-fatwani do it
